name: Benchmark Test
on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y clang cmake

      - name: Benchmark test
        run: |
          cmake --preset linux-bench -DBUILD_SHARED_LIBS=on
          cmake --build --preset linux-bench --target sear
          cmake --build --preset linux-bench --target bench_runner

      - name: Run Benchmarks
        run: ./build/linux/bench_runner > benchmark_results.json

      - name: Format Results to Markdown
        id: format_results
        run: |
          # Use jq to build a Markdown table string from your JSON
          echo "TABLE_DATA<<EOF" >> $GITHUB_ENV
          echo "| Benchmark | Avg Time (ms) | Memory Growth (KB) |" >> $GITHUB_ENV
          echo "|-----------|----------------|---------------------|" >> $GITHUB_ENV
          jq -r '.[] | "| \(.name) | \(.avg_time_ms) | \(.mem_growth_kb) |"' benchmark_results.json >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Comment to PR
        uses: mshick/add-pr-comment@v3
        id: comment
        with:
          message: |
            ### 🚀 Benchmark Results
            ${{ env.TABLE_DATA }}
      - name: Check outputs
        run: |
          echo "Comment created: ${{ steps.comment.outputs.comment-created }}"
          echo "Comment updated: ${{ steps.comment.outputs.comment-updated }}"
          echo "Comment ID: ${{ steps.comment.outputs.comment-id }}"